---
- name: Delete the virtual server
  hosts: f5
  connection: local

  tasks
  - name: Delete virtual server
    bigip_virtual_server:
      name: VS1
      partition: Common
      state: absent
      provider:
        server: "{{ ansible_host }}"
        server_port: "{{ bigip_port }}"
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"
        validate_certs: "{{ validate_certs }}"
    delegate_to: localhost

